[tool.poetry]
name = "monorepo"
version = "0.1.0"
description = ""
authors = ["Jack Cho <jack06215@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
# python version
# `dagster-slack` requires python > 3.11 and < 3.13
python = ">3.11,<3.13"
# pip install version
databases = { extras = ["postgresql"], version = "^0.9.0" }
fastapi = "^0.115.12"
psycopg2-binary = "2.9.10"
pydantic = "^2.11.3"
numpy = "^2.2.4"
pandas = "^2.2.3"
python-dotenv = "^1.0.0"
pytz = "^2025.2"
starlette = "^0.46.1"
uvicorn = "^0.34.0"
dagster = "^1.10.10"
dagster-slack = "^0.26.10"
dagster-webserver = "^1.10.10"
slack-client = "^0.3.0"
duckdb = "^1.2.2"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "<8.2.0"
pandas-stubs = ">=2.2.2.0,<2.2.4"
types-requests = "<2.23.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
