[tool.poetry]
name = "monorepo"
version = "0.1.0"
description = ""
authors = ["Jack Cho <jack06215@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.11.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
