#!/usr/bin/env bash
# Runs every `.check` target generated by rules/cpp/lint:defs.bzl (cc_test
# wrapper) across the repo. Scoped by the "cpp_lint" tag rather than the
# "//python/leetcode_algorithm/..." package or the ".fix"/".check" name
# suffix alone, since python's lint macro also produces ".fix"-suffixed
# targets and the C++ sources currently live inside a package named
# "python/leetcode_algorithm". Must be invoked with `bazel run`: nested bazel
# invocations from inside a sandboxed build/test action can deadlock against
# the running server, so this shells out at run time instead.
set -euo pipefail

if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo "error: run this target with 'bazel run', not 'bazel build/test'" >&2
  exit 1
fi

bazel_bin="$(command -v bazelisk || command -v bazel)"
cd "${BUILD_WORKSPACE_DIRECTORY}"

targets="$("${bazel_bin}" query 'kind(sh_test, attr(tags, "cpp_lint", //...))' 2>/dev/null)"
if [[ -z "${targets}" ]]; then
  echo "no .check targets found"
  exit 0
fi

# Target labels never contain whitespace, so word-splitting here is safe.
# shellcheck disable=SC2086
exec "${bazel_bin}" test ${targets}
