#!/usr/bin/env bash
# Runs every `.fix` target generated by rules/cpp/lint:defs.bzl (cc_test
# wrapper) across the repo, one at a time since each one edits real files in
# the workspace. Scoped by the "cpp_lint" tag (see check_all.sh for why: the
# ".fix" name suffix alone is shared with python's lint macro). Must be
# invoked with `bazel run`.
set -euo pipefail

if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo "error: run this target with 'bazel run', not 'bazel build/test'" >&2
  exit 1
fi

bazel_bin="$(command -v bazelisk || command -v bazel)"
cd "${BUILD_WORKSPACE_DIRECTORY}"

targets="$("${bazel_bin}" query 'kind(sh_binary, attr(tags, "cpp_lint", //...))' 2>/dev/null)"
if [[ -z "${targets}" ]]; then
  echo "no .fix targets found"
  exit 0
fi

status=0
# Target labels never contain whitespace, so word-splitting here is safe.
for target in ${targets}; do
  echo "== ${target} =="
  "${bazel_bin}" run "${target}" || status=$?
done
exit "${status}"
