#!/usr/bin/env bash
# Runs every `.fix` target generated by rules/python/lint:defs.bzl (py_library /
# py_binary wrappers) under //packages/..., one at a time since each one edits
# real files in the workspace. Must be invoked with `bazel run`.
set -euo pipefail

if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo "error: run this target with 'bazel run', not 'bazel build/test'" >&2
  exit 1
fi

bazel_bin="$(command -v bazelisk || command -v bazel)"
cd "${BUILD_WORKSPACE_DIRECTORY}"

targets="$("${bazel_bin}" query 'attr(name, "\.fix$", //packages/...)' 2>/dev/null)"
if [[ -z "${targets}" ]]; then
  echo "no .fix targets found under //packages/..."
  exit 0
fi

status=0
# Target labels never contain whitespace, so word-splitting here is safe.
for target in ${targets}; do
  echo "== ${target} =="
  "${bazel_bin}" run "${target}" || status=$?
done
exit "${status}"
